#!/bin/sh
#
# @name Typhoon H480 SITL
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

param set-default MC_PITCHRATE_P 0.0800
param set-default MC_PITCHRATE_I 0.0400
param set-default MC_PITCHRATE_D 0.0010
param set-default MC_PITCH_P 9.0
param set-default MC_ROLLRATE_P 0.0800
param set-default MC_ROLLRATE_I 0.0400
param set-default MC_ROLLRATE_D 0.0010
param set-default MC_ROLL_P 9.0
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_P_ACC 3

param set-default RTL_DESCEND_ALT 10

param set-default TRIG_INTERFACE 3
param set-default TRIG_MODE 4
param set-default MNT_MODE_IN 4
param set-default MNT_MODE_OUT 2
param set-default MAV_PROTO_VER 2

# GPS和EKF2参数配置
param set-default EKF2_AID_MASK 1
param set-default EKF2_HGT_MODE 1
param set-default EKF2_GPS_TYPE 0
param set-default EKF2_GPS_P_NOISE 0.5
param set-default EKF2_GPS_V_NOISE 0.5
param set-default EKF2_GPS_P_GATE 5.0
param set-default EKF2_GPS_V_GATE 5.0
param set-default EKF2_MAG_TYPE 1
param set-default EKF2_BETA_GATE 5.0
param set-default EKF2_BETA_NOISE 0.3
param set-default EKF2_HGT_REF_MODE 0
param set-default EKF2_BARO_GATE 5.0
param set-default EKF2_RNG_GATE 5.0
param set-default EKF2_MAG_CAL 1
param set-default EKF2_GSF_TAS 15.0
param set-default EKF2_ASPD_MAX 20.0
param set-default EKF2_POSNE_M_NSE 0.1
param set-default EKF2_VELD_M_NSE 0.1
param set-default EKF2_VELNE_M_NSE 0.1
param set-default EKF2_GPS_CHECK 1
param set-default EKF2_REQ_GPS_H 10.0
param set-default EKF2_REQ_SACC 1.0
param set-default EKF2_REQ_HDRIFT 0.3

set MIXER hexa_x
